### ISSUE TITLE
Fazer o ícone (logo) do app

### ISSUE THREAD

**Issue by BiancaArantes28** [BiancaArantes28/SOSAnimal#2]

**Comment by marinhobmaria** [comment]
**Boa noite.**

Estamos alinhando o ícone, de uma forma democrática onde cada integrante do grupo irá apresentar sua idéia, e iremos realizar a votação(dentro do grupo de UX) que irá definir e disponibilizaremos ao grupo antes da apresentação oficial ao professor.

**Comment by marinhobmaria** [comment]
**Ícone entregue conforme mensagens enviadas à todo o grupo.**

**Comment by marinhobmaria** [comment]
Finalizada.
